### ISSUE TITLE
Static Registration Form

### ISSUE THREAD

**Issue by BTBTravis** [redi-js-teachers/js_sprint_2020_final_project_stankasvecova#6]
Hey @stankasvecova great work so far. Please create a static registration form with html and css for your goodteens app. 

- [x] basic html form with named fields and labels
- [x] css styling on form

In the pull request you create to do this please mention this issue by putting `solves: #6` in the description of the pull request.

**Comment by MrTim** [comment]
Closing this issue since it's done :+1:
