### ISSUE TITLE
Video feed block

### ISSUE THREAD

**Issue by stankasvecova** [redi-js-teachers/js_sprint_2020_final_project_stankasvecova#9]
Hi guys.

A question: if I want a dynamic video feed on the homepage (each video tagged under specific hobby), where to start? what feature/solution do the best content-aggregation websites use? should I implement API here or something else?

Say I identify 10 youtube channels. Whenever one of those channels uploads a new video on youtube, it gets dynamically displayed and tagged on my website. 

Please throw any resources and suggestions what I should read up on. Thanks

**Comment by BTBTravis** [comment]
Hey @stankasvecova I thought the original idea was users of the sites create the video blocks?

**Comment by BTBTravis** [comment]
It does seem possible to subscribe to push notifications when a public channel releases a video.

Docs here: https://developers.google.com/youtube/v3/guides/push_notifications

## What we would need for something like this?
- somewhere to store ids of channels you want to get notifications
  - if it is just you picking channels we could use airtable pretty easily
  - if it is users of your app that are are providing the channel ids then we would need db in the backend
- backend server that is constantly running and open to the internet to receive notifications via webhook url from google
- backend would have to store these notifications / convert them into video blocks and save them to a database


This is quite a complex feature I would start with just letting users author video blocks, much easier.

**Comment by MrTim** [comment]
Agree with @BTBTravis, this is quite a complex topic. If we understand it correctly.
We can do [embedding](https://support.google.com/youtube/answer/171780?hl=en) of needed channels as well. This would be predefined for start and wont require any backend for now. I believe new videos should be available as soon as they are on youtube.
But I didn't check and use it before.

**Comment by stankasvecova** [comment]
Yes you do understand it correctly.
The user will have the ability to create a video block,
But at the same time the website cannot rely on users' unpredictable behavior for new videos; thus it should be also picking selected channels' content. 
Yes, whatever from this is easier, will be first on the to-do-list. 
Thanks for the link, will study.

**Comment by stankasvecova** [comment]
So, according to the link, the first step is to: 
[ ] Set up a callback server that can handle incoming Atom feed notifications.

Anyone could give me hints on how to start?
Is it OK to use php or would you recommend to go a different way?

It seems it gives people troubles but I want to give it a try:
https://stackoverflow.com/questions/29611459/youtube-api-subscribing-to-push-notifications
https://issuetracker.google.com/issues/35175433

Thanks!

**Comment by BTBTravis** [comment]
Hey @stankasvecova I just checkout your project and I only see a registration form. Please create a video feed page that paints via javascript from an array of video ideas then we'll figure out a backend.. 

If activepub and all that is to complicated I got an idea for a simple cron and rss solution. https://danielmiessler.com/blog/rss-feed-youtube-channel/

**Comment by BTBTravis** [comment]
#17 solved basic video block creation
